config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :challenges, only: %w[index show]
  resources :my_challenges, only: %w[index new create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  has_many :my_challenges, dependent: :destroy
end

app/models/my_challenge.rb
class MyChallenge < ApplicationRecord
  belongs_to :user
  belongs_to :challenge, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :my_challenges, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  skip_before_action :verify_authenticity_token

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo_url])

    devise_parameter_sanitizer.permit(:account_update, keys: [:photo_url])
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  def index
    @challenges = Challenge.all
  end

  def show
    @challenge = Challenge.find(params[:id])
  end
end

app/controllers/my_challenges_controller.rb
class MyChallengesController < ApplicationController
  def index
    # Get all the My challenges where the user id matches current user
    @my_challenges = MyChallenge.all
  end

  def new
  end

  def create
    my_challenge = MyChallenge.create(challenge_id: params[:id], user_id: current_user.id)
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  # skip_before_action :verify_authenticity_token

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/challenges/index.html.erb
<div class="container container-cards">
  <% @challenges.each do |challenge|%>
    <%= link_to(challenge_path(challenge), class: "card-challenge") do %>
      <img src= "<%= challenge.poster_url %>", alt="Challenge poster">
      <div class="card-challenge-infos">
        <h2> <%= challenge.title %> </h2>
        <p> <%= challenge.description %> </p>
      </div>
      <div class="card-challenge-category">
        <img src="/images/mental_fitness.svg" alt="category">
      </div>
    <% end %>
  <% end %>
</div>

app/views/challenges/show.html.erb
<div class="container">
  <h1> <%= @challenge.title %></h1>
  <img src="<%= @challenge.poster_url %>" alt="Challenge Photo">
  <div class="show-info">
    <p><%= @challenge.description %></p>
    <%= form_with url:my_challenges_path, method: :post do |f| %>
      <%= f.text_field :id, type: :hidden, value: @challenge.id %>
      <%= f.submit 'Add this challenge!', :class => 'btn-follow' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChallengeCity</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Lato:wght@300&family=Work+Sans:wght@400;500;600;700&display=swap');
    </style>
    <link rel="stylesheet" href="../..assets/stylesheets/pages/application.scss">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <nav>
      <%= render "shared/navbar" %>
    </nav>
      <%= render "shared/flashes" %>
      <%# <p class="notice"><%= notice %>
      <%# <p class="alert"><%= alert %>
      <main>
        <%= yield %>
      </main>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/my_challenges/create.html.erb
<h1>MyChallenges#create</h1>
<p>Find me in app/views/my_challenges/create.html.erb</p>

app/views/my_challenges/destroy.html.erb
<h1>MyChallenges#destroy</h1>
<p>Find me in app/views/my_challenges/destroy.html.erb</p>

app/views/my_challenges/index.html.erb
<h1>MyChallenges</h1>

<% @my_challenges.each do |challenge| %>
  <h3><%= Challenge.find(challenge.challenge_id).title %></h3>
  <img src="<%= Challenge.find(challenge.challenge_id).poster_url %>" alt="Challenge photo">
<% end %>

app/views/my_challenges/new.html.erb
<h1>MyChallenges#new</h1>
<p>Find me in app/views/my_challenges/new.html.erb</p>

app/views/pages/home.html.erb
<div class="container d-flex justify-space-between">
  <div class="photo-landing">
    <img src="https://images.unsplash.com/photo-1517455160094-397f79c8cc39?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxjb2xsZWN0aW9uLXBhZ2V8OTB8NjE1NTc0fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60" alt="Challenge Photo">
  </div>
  <div class="container-landing-info">
    <h1>Welcome to Challenge City!</h1>
    <h3>Find inspiration for a 30-day challenge that will put you out of your comfort zone and maybe even crate a great new habit!</h3>
    <%= link_to "Find Your Next Challenge", challenges_path, class: "button-primary" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", challenges_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://c8d8q6i8.stackpathcdn.com/wp-content/uploads/2020/12/Tim-Robinson.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Challenges", my_challenges_path, class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>